import { sqliteTable, text, integer, index, uniqueIndex, check } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
import { pkUuid, ts, tsNow, bool } from './_shared';
import { users } from './core';

export const COACH_ROLES = ['user', 'assistant', 'system'] as const;
export const INSIGHT_DOMAINS = ['nutrition', 'training', 'sleep', 'body', 'overall'] as const;
export const INSIGHT_SEVERITIES = ['info', 'warning', 'alert'] as const;

export const coachConversations = sqliteTable('coach_conversations', {
  id: pkUuid(),
  userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  title: text('title'),
  lastMessageAt: ts('last_message_at'),
  messageCount: integer('message_count').notNull().default(0),
  isArchived: bool('is_archived', false),
  createdAt: tsNow('created_at'),
  updatedAt: tsNow('updated_at'),
}, (t) => [
  index('coach_conversations_user_idx').on(t.userId, t.lastMessageAt),
]);

export const coachMessages = sqliteTable('coach_messages', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  conversationId: text('conversation_id').notNull()
    .references(() => coachConversations.id, { onDelete: 'cascade' }),
  role: text('role', { enum: COACH_ROLES }).notNull(),
  content: text('content').notNull(),
  /** Photo the user attached to this message (media_assets.id, kind coach_photo). */
  photoAssetId: text('photo_asset_id'),
  /** Snapshot of the health data injected into this turn — makes answers reproducible.
   *  On user messages it holds { photoDescription } so later turns' history still
   *  "sees" a photo that has long scrolled out of the model's vision. */
  contextJson: text('context_json'),
  model: text('model'),
  promptTokens: integer('prompt_tokens'),
  completionTokens: integer('completion_tokens'),
  latencyMs: integer('latency_ms'),
  createdAt: tsNow('created_at'),
}, (t) => [
  index('coach_messages_conversation_idx').on(t.conversationId),
  check('coach_messages_role_ck', sql`${t.role} in ('user','assistant','system')`),
]);

/** Proactive coaching generated by cron: deficit trends, sleep debt, load, goals. */
export const coachInsights = sqliteTable('coach_insights', {
  id: pkUuid(),
  userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  domain: text('domain', { enum: INSIGHT_DOMAINS }).notNull(),
  localDate: text('local_date').notNull(),
  period: text('period').notNull(),
  title: text('title').notNull(),
  body: text('body').notNull(),
  severity: text('severity', { enum: INSIGHT_SEVERITIES }),
  /** Optional deep link: {"type":"open_meal_plan","id":"..."} */
  actionJson: text('action_json'),
  model: text('model'),
  isRead: bool('is_read', false),
  createdAt: tsNow('created_at'),
}, (t) => [
  index('coach_insights_user_date_idx').on(t.userId, t.localDate),
]);

export const COACH_ACTION_STATUSES = ['pending', 'confirmed', 'cancelled', 'failed', 'expired'] as const;

/**
 * A write the assistant proposed. The agent only ever creates these; the
 * user's confirm executes `tool` with `argsJson` through the public API.
 */
export const coachActions = sqliteTable('coach_actions', {
  id: pkUuid(),
  userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  conversationId: text('conversation_id').notNull()
    .references(() => coachConversations.id, { onDelete: 'cascade' }),
  /** The assistant reply that carries the confirm card; set once the reply is stored. */
  messageId: integer('message_id').references(() => coachMessages.id, { onDelete: 'set null' }),
  tool: text('tool').notNull(),
  argsJson: text('args_json').notNull(),
  /** Written by code from the validated arguments, never by the model. */
  summary: text('summary').notNull(),
  detailsJson: text('details_json'),
  status: text('status', { enum: COACH_ACTION_STATUSES }).notNull().default('pending'),
  resultJson: text('result_json'),
  errorMessage: text('error_message'),
  createdAt: tsNow('created_at'),
  resolvedAt: ts('resolved_at'),
}, (t) => [
  index('coach_actions_conversation_idx').on(t.conversationId),
  index('coach_actions_user_idx').on(t.userId, t.createdAt),
  check('coach_actions_status_ck', sql`${t.status} in ('pending','confirmed','cancelled','failed','expired')`),
]);

export const FACT_CATEGORIES = [
  'health', 'nutrition', 'training', 'sleep', 'preference', 'other',
] as const;

/**
 * What the assistant has learned about this user and should still know next
 * week: allergies, injuries, chronic conditions, what they hate eating, when
 * they train, why they are cutting.
 *
 * Two lifetimes live in one table. A fact with `expires_at` null is permanent
 * ("dị ứng hải sản"); one with a timestamp is true only for a while ("đang
 * chấn thương gối, nghỉ chạy 3 tuần"), and every read filters the expired ones
 * out rather than trusting a sweeper to have run — see services/agent/memory.ts.
 *
 * `fact_key` is the normalised text, unique per user: remembering the same
 * thing twice updates the row (and can extend or clear its expiry) instead of
 * stacking near-duplicates the model then has to read past.
 */
export const userFacts = sqliteTable('user_facts', {
  id: pkUuid(),
  userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  category: text('category', { enum: FACT_CATEGORIES }).notNull().default('other'),
  /** One sentence, in the user's own terms. */
  fact: text('fact').notNull(),
  /** Normalised `fact`, for the per-user uniqueness above. */
  factKey: text('fact_key').notNull(),
  /** Null means it never expires. */
  expiresAt: ts('expires_at'),
  /** Where it came from — only the assistant writes facts today. */
  source: text('source').notNull().default('assistant'),
  conversationId: text('conversation_id'),
  createdAt: tsNow('created_at'),
  updatedAt: tsNow('updated_at'),
}, (t) => [
  uniqueIndex('user_facts_key_uq').on(t.userId, t.factKey),
  index('user_facts_user_idx').on(t.userId, t.expiresAt),
  check('user_facts_category_ck',
    sql`${t.category} in ('health','nutrition','training','sleep','preference','other')`),
]);
