import { sqliteTable, text, integer, index, check } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
import { pkUuid, ts, tsNow, bool } from './_shared';
import { users } from './core';

export const COACH_ROLES = ['user', 'assistant', 'system'] as const;
export const INSIGHT_DOMAINS = ['nutrition', 'training', 'sleep', 'body', 'overall'] as const;
export const INSIGHT_SEVERITIES = ['info', 'warning', 'alert'] as const;

export const coachConversations = sqliteTable('coach_conversations', {
  id: pkUuid(),
  userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  title: text('title'),
  lastMessageAt: ts('last_message_at'),
  messageCount: integer('message_count').notNull().default(0),
  isArchived: bool('is_archived', false),
  createdAt: tsNow('created_at'),
  updatedAt: tsNow('updated_at'),
}, (t) => [
  index('coach_conversations_user_idx').on(t.userId, t.lastMessageAt),
]);

export const coachMessages = sqliteTable('coach_messages', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  conversationId: text('conversation_id').notNull()
    .references(() => coachConversations.id, { onDelete: 'cascade' }),
  role: text('role', { enum: COACH_ROLES }).notNull(),
  content: text('content').notNull(),
  /** Snapshot of the health data injected into this turn — makes answers reproducible. */
  contextJson: text('context_json'),
  model: text('model'),
  promptTokens: integer('prompt_tokens'),
  completionTokens: integer('completion_tokens'),
  latencyMs: integer('latency_ms'),
  createdAt: tsNow('created_at'),
}, (t) => [
  index('coach_messages_conversation_idx').on(t.conversationId),
  check('coach_messages_role_ck', sql`${t.role} in ('user','assistant','system')`),
]);

/** Proactive coaching generated by cron: deficit trends, sleep debt, load, goals. */
export const coachInsights = sqliteTable('coach_insights', {
  id: pkUuid(),
  userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  domain: text('domain', { enum: INSIGHT_DOMAINS }).notNull(),
  localDate: text('local_date').notNull(),
  period: text('period').notNull(),
  title: text('title').notNull(),
  body: text('body').notNull(),
  severity: text('severity', { enum: INSIGHT_SEVERITIES }),
  /** Optional deep link: {"type":"open_meal_plan","id":"..."} */
  actionJson: text('action_json'),
  model: text('model'),
  isRead: bool('is_read', false),
  createdAt: tsNow('created_at'),
}, (t) => [
  index('coach_insights_user_date_idx').on(t.userId, t.localDate),
]);
