-- ChipHealth seed data: fixed catalogs + their i18n names + starter Vietnamese foods.
-- Idempotent: every statement is INSERT OR IGNORE, keyed on the natural unique.
-- Run with: npm run db:seed:local

PRAGMA foreign_keys = ON;

-- ============ activity_types ============
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (1, 'running', 'cardio_gps', 9.8, 1, 0, 1, 'run', 10, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (2, 'trail_running', 'cardio_gps', 10.5, 1, 0, 1, 'trail', 20, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (3, 'treadmill', 'cardio_indoor', 9, 0, 0, 1, 'treadmill', 30, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (4, 'walking', 'cardio_gps', 3.5, 1, 0, 1, 'walk', 40, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (5, 'hiking', 'cardio_gps', 6, 1, 0, 1, 'hike', 50, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (6, 'trekking', 'cardio_gps', 7, 1, 0, 1, 'trek', 60, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (7, 'cycling', 'cardio_gps', 8, 1, 0, 1, 'bike', 70, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (8, 'mountain_biking', 'cardio_gps', 8.5, 1, 0, 1, 'mtb', 80, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (9, 'indoor_cycling', 'cardio_indoor', 7, 0, 0, 1, 'bike_indoor', 90, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (10, 'spinning', 'cardio_indoor', 8.5, 0, 0, 1, 'spinning', 100, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (11, 'swimming', 'cardio_indoor', 8.3, 0, 0, 1, 'swim', 110, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (12, 'open_water_swimming', 'cardio_gps', 9.5, 1, 0, 1, 'swim_open', 120, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (13, 'rowing', 'cardio_indoor', 7, 0, 0, 1, 'row', 130, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (14, 'kayaking', 'cardio_gps', 5, 1, 0, 1, 'kayak', 140, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (15, 'elliptical', 'cardio_indoor', 5, 0, 0, 1, 'elliptical', 150, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (16, 'stair_climbing', 'cardio_indoor', 9, 0, 0, 1, 'stairs', 160, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (17, 'jump_rope', 'cardio_indoor', 12.3, 0, 0, 1, 'jump_rope', 170, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (18, 'skiing', 'cardio_gps', 7, 1, 0, 1, 'ski', 180, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (19, 'snowboarding', 'cardio_gps', 5.3, 1, 0, 1, 'snowboard', 190, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (20, 'gym_strength', 'strength', 6, 0, 1, 1, 'dumbbell', 200, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (21, 'powerlifting', 'strength', 6, 0, 1, 1, 'barbell', 210, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (22, 'bodyweight_training', 'strength', 4.5, 0, 1, 1, 'bodyweight', 220, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (23, 'calisthenics', 'strength', 5, 0, 1, 1, 'calisthenics', 230, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (24, 'crossfit', 'strength', 8, 0, 1, 1, 'crossfit', 240, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (25, 'kettlebell', 'strength', 8, 0, 1, 1, 'kettlebell', 250, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (26, 'circuit_training', 'strength', 7.5, 0, 1, 1, 'circuit', 260, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (27, 'badminton', 'sport', 7, 0, 0, 1, 'badminton', 270, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (28, 'football', 'sport', 8, 1, 0, 1, 'football', 280, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (29, 'futsal', 'sport', 8.5, 0, 0, 1, 'futsal', 290, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (30, 'tennis', 'sport', 7.3, 0, 0, 1, 'tennis', 300, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (31, 'table_tennis', 'sport', 4, 0, 0, 1, 'table_tennis', 310, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (32, 'pickleball', 'sport', 5.5, 0, 0, 1, 'pickleball', 320, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (33, 'squash', 'sport', 12, 0, 0, 1, 'squash', 330, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (34, 'basketball', 'sport', 8, 0, 0, 1, 'basketball', 340, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (35, 'volleyball', 'sport', 4, 0, 0, 1, 'volleyball', 350, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (36, 'golf', 'sport', 4.8, 1, 0, 1, 'golf', 360, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (37, 'boxing', 'sport', 9, 0, 0, 1, 'boxing', 370, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (38, 'muay_thai', 'sport', 10, 0, 0, 1, 'muay_thai', 380, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (39, 'martial_arts', 'sport', 10.3, 0, 0, 1, 'martial_arts', 390, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (40, 'climbing', 'sport', 8, 0, 0, 1, 'climbing', 400, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (41, 'skateboarding', 'sport', 5, 0, 0, 1, 'skateboard', 410, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (42, 'roller_skating', 'sport', 7, 1, 0, 1, 'roller_skate', 420, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (43, 'surfing', 'sport', 3, 0, 0, 1, 'surf', 430, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (44, 'horse_riding', 'sport', 5.5, 1, 0, 1, 'horse', 440, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (45, 'dancing', 'sport', 7.8, 0, 0, 1, 'dance', 450, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (46, 'yoga', 'mind_body', 2.5, 0, 0, 1, 'yoga', 460, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (47, 'pilates', 'mind_body', 3, 0, 0, 1, 'pilates', 470, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (48, 'stretching', 'mind_body', 2.3, 0, 0, 1, 'stretch', 480, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (49, 'tai_chi', 'mind_body', 3, 0, 0, 1, 'tai_chi', 490, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (50, 'meditation', 'mind_body', 1.3, 0, 0, 1, 'meditation', 500, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (51, 'breathing_exercise', 'mind_body', 1.5, 0, 0, 1, 'breathing', 510, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (52, 'physical_therapy', 'other', 3, 0, 0, 1, 'therapy', 520, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (53, 'housework', 'other', 3.3, 0, 0, 1, 'home', 530, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (54, 'gardening', 'other', 3.8, 0, 0, 1, 'garden', 540, 1);
INSERT OR IGNORE INTO activity_types (id, code, category, default_met, supports_gps, supports_sets, supports_heart_rate, icon_name, sort_order, is_active) VALUES (55, 'other_workout', 'other', 4, 0, 0, 1, 'other', 550, 1);

-- ============ workout_exercises ============
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (1, 'bench_press', 'chest', 'barbell', 0, 10);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (2, 'incline_bench_press', 'chest', 'barbell', 0, 20);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (3, 'decline_bench_press', 'chest', 'barbell', 0, 30);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (4, 'dumbbell_press', 'chest', 'dumbbell', 0, 40);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (5, 'incline_dumbbell_press', 'chest', 'dumbbell', 0, 50);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (6, 'chest_fly', 'chest', 'dumbbell', 0, 60);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (7, 'cable_crossover', 'chest', 'cable', 0, 70);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (8, 'push_up', 'chest', 'bodyweight', 0, 80);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (9, 'chest_dip', 'chest', 'bodyweight', 0, 90);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (10, 'deadlift', 'back', 'barbell', 0, 100);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (11, 'barbell_row', 'back', 'barbell', 0, 110);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (12, 'pull_up', 'back', 'bodyweight', 0, 120);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (13, 'chin_up', 'back', 'bodyweight', 0, 130);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (14, 'lat_pulldown', 'back', 'machine', 0, 140);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (15, 'seated_cable_row', 'back', 'cable', 0, 150);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (16, 't_bar_row', 'back', 'barbell', 0, 160);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (17, 'single_arm_dumbbell_row', 'back', 'dumbbell', 1, 170);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (18, 'face_pull', 'back', 'cable', 0, 180);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (19, 'back_squat', 'legs', 'barbell', 0, 190);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (20, 'front_squat', 'legs', 'barbell', 0, 200);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (21, 'leg_press', 'legs', 'machine', 0, 210);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (22, 'romanian_deadlift', 'legs', 'barbell', 0, 220);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (23, 'walking_lunge', 'legs', 'dumbbell', 1, 230);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (24, 'bulgarian_split_squat', 'legs', 'dumbbell', 1, 240);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (25, 'leg_extension', 'legs', 'machine', 0, 250);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (26, 'leg_curl', 'legs', 'machine', 0, 260);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (27, 'calf_raise', 'legs', 'machine', 0, 270);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (28, 'hip_thrust', 'legs', 'barbell', 0, 280);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (29, 'overhead_press', 'shoulders', 'barbell', 0, 290);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (30, 'dumbbell_shoulder_press', 'shoulders', 'dumbbell', 0, 300);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (31, 'arnold_press', 'shoulders', 'dumbbell', 0, 310);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (32, 'lateral_raise', 'shoulders', 'dumbbell', 0, 320);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (33, 'front_raise', 'shoulders', 'dumbbell', 0, 330);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (34, 'rear_delt_fly', 'shoulders', 'dumbbell', 0, 340);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (35, 'upright_row', 'shoulders', 'barbell', 0, 350);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (36, 'barbell_curl', 'arms', 'barbell', 0, 360);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (37, 'dumbbell_curl', 'arms', 'dumbbell', 1, 370);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (38, 'hammer_curl', 'arms', 'dumbbell', 1, 380);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (39, 'preacher_curl', 'arms', 'machine', 0, 390);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (40, 'tricep_pushdown', 'arms', 'cable', 0, 400);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (41, 'skull_crusher', 'arms', 'barbell', 0, 410);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (42, 'overhead_tricep_extension', 'arms', 'dumbbell', 0, 420);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (43, 'plank', 'core', 'bodyweight', 0, 430);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (44, 'side_plank', 'core', 'bodyweight', 1, 440);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (45, 'crunch', 'core', 'bodyweight', 0, 450);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (46, 'hanging_leg_raise', 'core', 'bodyweight', 0, 460);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (47, 'russian_twist', 'core', 'bodyweight', 0, 470);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (48, 'cable_woodchop', 'core', 'cable', 1, 480);
INSERT OR IGNORE INTO workout_exercises (id, code, muscle_group, equipment, is_unilateral, sort_order) VALUES (49, 'ab_wheel_rollout', 'core', 'bodyweight', 0, 490);

-- ============ translations: activity type names ============
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '1', 'vi', 'name', 'Chạy bộ');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '1', 'en', 'name', 'Running');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '2', 'vi', 'name', 'Chạy địa hình');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '2', 'en', 'name', 'Trail running');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '3', 'vi', 'name', 'Chạy máy');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '3', 'en', 'name', 'Treadmill');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '4', 'vi', 'name', 'Đi bộ');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '4', 'en', 'name', 'Walking');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '5', 'vi', 'name', 'Đi bộ đường dài');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '5', 'en', 'name', 'Hiking');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '6', 'vi', 'name', 'Trekking');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '6', 'en', 'name', 'Trekking');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '7', 'vi', 'name', 'Đạp xe');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '7', 'en', 'name', 'Cycling');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '8', 'vi', 'name', 'Đạp xe địa hình');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '8', 'en', 'name', 'Mountain biking');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '9', 'vi', 'name', 'Đạp xe trong nhà');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '9', 'en', 'name', 'Indoor cycling');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '10', 'vi', 'name', 'Spinning');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '10', 'en', 'name', 'Spinning');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '11', 'vi', 'name', 'Bơi lội');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '11', 'en', 'name', 'Swimming');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '12', 'vi', 'name', 'Bơi ngoài trời');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '12', 'en', 'name', 'Open water swimming');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '13', 'vi', 'name', 'Chèo thuyền máy');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '13', 'en', 'name', 'Rowing');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '14', 'vi', 'name', 'Chèo kayak');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '14', 'en', 'name', 'Kayaking');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '15', 'vi', 'name', 'Máy tập elliptical');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '15', 'en', 'name', 'Elliptical');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '16', 'vi', 'name', 'Leo cầu thang');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '16', 'en', 'name', 'Stair climbing');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '17', 'vi', 'name', 'Nhảy dây');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '17', 'en', 'name', 'Jump rope');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '18', 'vi', 'name', 'Trượt tuyết');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '18', 'en', 'name', 'Skiing');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '19', 'vi', 'name', 'Trượt ván tuyết');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '19', 'en', 'name', 'Snowboarding');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '20', 'vi', 'name', 'Tập gym');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '20', 'en', 'name', 'Gym strength');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '21', 'vi', 'name', 'Cử tạ');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '21', 'en', 'name', 'Powerlifting');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '22', 'vi', 'name', 'Tập với trọng lượng cơ thể');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '22', 'en', 'name', 'Bodyweight training');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '23', 'vi', 'name', 'Calisthenics');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '23', 'en', 'name', 'Calisthenics');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '24', 'vi', 'name', 'CrossFit');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '24', 'en', 'name', 'CrossFit');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '25', 'vi', 'name', 'Tạ ấm');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '25', 'en', 'name', 'Kettlebell');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '26', 'vi', 'name', 'Tập vòng tròn');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '26', 'en', 'name', 'Circuit training');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '27', 'vi', 'name', 'Cầu lông');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '27', 'en', 'name', 'Badminton');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '28', 'vi', 'name', 'Bóng đá');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '28', 'en', 'name', 'Football');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '29', 'vi', 'name', 'Bóng đá sân nhỏ');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '29', 'en', 'name', 'Futsal');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '30', 'vi', 'name', 'Quần vợt');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '30', 'en', 'name', 'Tennis');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '31', 'vi', 'name', 'Bóng bàn');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '31', 'en', 'name', 'Table tennis');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '32', 'vi', 'name', 'Pickleball');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '32', 'en', 'name', 'Pickleball');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '33', 'vi', 'name', 'Squash');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '33', 'en', 'name', 'Squash');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '34', 'vi', 'name', 'Bóng rổ');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '34', 'en', 'name', 'Basketball');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '35', 'vi', 'name', 'Bóng chuyền');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '35', 'en', 'name', 'Volleyball');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '36', 'vi', 'name', 'Golf');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '36', 'en', 'name', 'Golf');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '37', 'vi', 'name', 'Boxing');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '37', 'en', 'name', 'Boxing');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '38', 'vi', 'name', 'Muay Thái');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '38', 'en', 'name', 'Muay Thai');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '39', 'vi', 'name', 'Võ thuật');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '39', 'en', 'name', 'Martial arts');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '40', 'vi', 'name', 'Leo núi');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '40', 'en', 'name', 'Climbing');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '41', 'vi', 'name', 'Trượt ván');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '41', 'en', 'name', 'Skateboarding');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '42', 'vi', 'name', 'Trượt patin');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '42', 'en', 'name', 'Roller skating');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '43', 'vi', 'name', 'Lướt sóng');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '43', 'en', 'name', 'Surfing');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '44', 'vi', 'name', 'Cưỡi ngựa');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '44', 'en', 'name', 'Horse riding');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '45', 'vi', 'name', 'Khiêu vũ');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '45', 'en', 'name', 'Dancing');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '46', 'vi', 'name', 'Yoga');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '46', 'en', 'name', 'Yoga');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '47', 'vi', 'name', 'Pilates');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '47', 'en', 'name', 'Pilates');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '48', 'vi', 'name', 'Giãn cơ');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '48', 'en', 'name', 'Stretching');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '49', 'vi', 'name', 'Thái cực quyền');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '49', 'en', 'name', 'Tai chi');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '50', 'vi', 'name', 'Thiền');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '50', 'en', 'name', 'Meditation');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '51', 'vi', 'name', 'Bài tập thở');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '51', 'en', 'name', 'Breathing exercise');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '52', 'vi', 'name', 'Vật lý trị liệu');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '52', 'en', 'name', 'Physical therapy');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '53', 'vi', 'name', 'Việc nhà');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '53', 'en', 'name', 'Housework');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '54', 'vi', 'name', 'Làm vườn');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '54', 'en', 'name', 'Gardening');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '55', 'vi', 'name', 'Hoạt động khác');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('activity_types', '55', 'en', 'name', 'Other workout');

-- ============ translations: exercise names ============
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '1', 'vi', 'name', 'Đẩy ngực nằm với tạ đòn');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '1', 'en', 'name', 'Barbell bench press');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '2', 'vi', 'name', 'Đẩy ngực trên với tạ đòn');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '2', 'en', 'name', 'Incline barbell bench press');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '3', 'vi', 'name', 'Đẩy ngực dưới với tạ đòn');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '3', 'en', 'name', 'Decline barbell bench press');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '4', 'vi', 'name', 'Đẩy ngực với tạ đơn');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '4', 'en', 'name', 'Dumbbell bench press');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '5', 'vi', 'name', 'Đẩy ngực trên với tạ đơn');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '5', 'en', 'name', 'Incline dumbbell press');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '6', 'vi', 'name', 'Ép ngực với tạ đơn');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '6', 'en', 'name', 'Dumbbell chest fly');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '7', 'vi', 'name', 'Ép ngực cáp');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '7', 'en', 'name', 'Cable crossover');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '8', 'vi', 'name', 'Hít đất');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '8', 'en', 'name', 'Push-up');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '9', 'vi', 'name', 'Xà kép ngực');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '9', 'en', 'name', 'Chest dip');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '10', 'vi', 'name', 'Kéo tạ đất');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '10', 'en', 'name', 'Deadlift');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '11', 'vi', 'name', 'Kéo tạ đòn');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '11', 'en', 'name', 'Barbell row');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '12', 'vi', 'name', 'Hít xà (bàn tay úp)');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '12', 'en', 'name', 'Pull-up');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '13', 'vi', 'name', 'Hít xà (bàn tay ngửa)');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '13', 'en', 'name', 'Chin-up');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '14', 'vi', 'name', 'Kéo xô');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '14', 'en', 'name', 'Lat pulldown');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '15', 'vi', 'name', 'Kéo cáp ngồi');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '15', 'en', 'name', 'Seated cable row');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '16', 'vi', 'name', 'Kéo tạ chữ T');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '16', 'en', 'name', 'T-bar row');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '17', 'vi', 'name', 'Kéo tạ đơn một tay');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '17', 'en', 'name', 'Single-arm dumbbell row');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '18', 'vi', 'name', 'Kéo cáp ngang mặt');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '18', 'en', 'name', 'Face pull');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '19', 'vi', 'name', 'Squat lưng');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '19', 'en', 'name', 'Back squat');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '20', 'vi', 'name', 'Squat trước');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '20', 'en', 'name', 'Front squat');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '21', 'vi', 'name', 'Đạp đùi');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '21', 'en', 'name', 'Leg press');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '22', 'vi', 'name', 'Kéo tạ Romania');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '22', 'en', 'name', 'Romanian deadlift');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '23', 'vi', 'name', 'Bước tấn di chuyển');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '23', 'en', 'name', 'Walking lunge');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '24', 'vi', 'name', 'Squat một chân kiểu Bulgaria');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '24', 'en', 'name', 'Bulgarian split squat');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '25', 'vi', 'name', 'Duỗi đùi trước');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '25', 'en', 'name', 'Leg extension');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '26', 'vi', 'name', 'Cuốn đùi sau');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '26', 'en', 'name', 'Leg curl');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '27', 'vi', 'name', 'Nhón bắp chân');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '27', 'en', 'name', 'Calf raise');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '28', 'vi', 'name', 'Đẩy hông');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '28', 'en', 'name', 'Hip thrust');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '29', 'vi', 'name', 'Đẩy vai qua đầu');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '29', 'en', 'name', 'Overhead press');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '30', 'vi', 'name', 'Đẩy vai với tạ đơn');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '30', 'en', 'name', 'Dumbbell shoulder press');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '31', 'vi', 'name', 'Đẩy vai kiểu Arnold');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '31', 'en', 'name', 'Arnold press');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '32', 'vi', 'name', 'Nâng tạ sang ngang');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '32', 'en', 'name', 'Lateral raise');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '33', 'vi', 'name', 'Nâng tạ trước mặt');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '33', 'en', 'name', 'Front raise');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '34', 'vi', 'name', 'Đẩy vai sau');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '34', 'en', 'name', 'Rear delt fly');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '35', 'vi', 'name', 'Kéo tạ dọc thân');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '35', 'en', 'name', 'Upright row');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '36', 'vi', 'name', 'Cuốn tay trước với tạ đòn');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '36', 'en', 'name', 'Barbell curl');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '37', 'vi', 'name', 'Cuốn tay trước với tạ đơn');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '37', 'en', 'name', 'Dumbbell curl');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '38', 'vi', 'name', 'Cuốn tay kiểu búa');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '38', 'en', 'name', 'Hammer curl');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '39', 'vi', 'name', 'Cuốn tay ghế Preacher');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '39', 'en', 'name', 'Preacher curl');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '40', 'vi', 'name', 'Đẩy cáp tay sau');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '40', 'en', 'name', 'Tricep pushdown');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '41', 'vi', 'name', 'Duỗi tay sau nằm');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '41', 'en', 'name', 'Skull crusher');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '42', 'vi', 'name', 'Duỗi tay sau qua đầu');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '42', 'en', 'name', 'Overhead tricep extension');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '43', 'vi', 'name', 'Plank');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '43', 'en', 'name', 'Plank');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '44', 'vi', 'name', 'Plank nghiêng');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '44', 'en', 'name', 'Side plank');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '45', 'vi', 'name', 'Gập bụng');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '45', 'en', 'name', 'Crunch');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '46', 'vi', 'name', 'Treo xà nâng chân');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '46', 'en', 'name', 'Hanging leg raise');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '47', 'vi', 'name', 'Xoay người kiểu Nga');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '47', 'en', 'name', 'Russian twist');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '48', 'vi', 'name', 'Xoay cáp chéo thân');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '48', 'en', 'name', 'Cable woodchop');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '49', 'vi', 'name', 'Lăn bánh xe tập bụng');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('workout_exercises', '49', 'en', 'name', 'Ab wheel rollout');

-- ============ foods: common Vietnamese dishes, per 100 g ============
-- source = admin_manual, is_verified = 1 so they outrank AI guesses at match time.
-- embedding_status = 'pending': the vector is created by the admin reindex / embedding-queue drain.
INSERT OR IGNORE INTO foods (id, barcode, name, brand, category, serving_size_g, serving_label, calories_kcal, protein_g, carbs_g, fat_g, saturated_fat_g, fiber_g, sugar_g, sodium_mg, cholesterol_mg, potassium_mg, calcium_mg, iron_mg, micronutrients_json, source, source_url, is_verified, embedding_status, created_by, created_at, updated_at) VALUES ('0193a000-0001-7000-8000-000000000001', NULL, 'Phở bò', NULL, 'noodle_soup', 100, '1 tô (~500 g)', 72, 4.8, 9.2, 1.9, 0.7, 0.5, 0.6, 420, 12, 95, 18, 0.9, NULL, 'admin_manual', NULL, 1, 'pending', NULL, 1767225600000, 1767225600000);
INSERT OR IGNORE INTO foods (id, barcode, name, brand, category, serving_size_g, serving_label, calories_kcal, protein_g, carbs_g, fat_g, saturated_fat_g, fiber_g, sugar_g, sodium_mg, cholesterol_mg, potassium_mg, calcium_mg, iron_mg, micronutrients_json, source, source_url, is_verified, embedding_status, created_by, created_at, updated_at) VALUES ('0193a000-0001-7000-8000-000000000002', NULL, 'Cơm tấm sườn nướng', NULL, 'rice_dish', 100, '1 đĩa (~400 g)', 182, 9.1, 22.4, 6.4, 2.2, 0.8, 2.1, 330, 28, 155, 22, 1.2, NULL, 'admin_manual', NULL, 1, 'pending', NULL, 1767225600000, 1767225600000);
INSERT OR IGNORE INTO foods (id, barcode, name, brand, category, serving_size_g, serving_label, calories_kcal, protein_g, carbs_g, fat_g, saturated_fat_g, fiber_g, sugar_g, sodium_mg, cholesterol_mg, potassium_mg, calcium_mg, iron_mg, micronutrients_json, source, source_url, is_verified, embedding_status, created_by, created_at, updated_at) VALUES ('0193a000-0001-7000-8000-000000000003', NULL, 'Bánh mì thịt', NULL, 'sandwich', 100, '1 ổ (~180 g)', 251, 10.4, 32.8, 8.6, 2.8, 1.9, 3.2, 540, 26, 175, 35, 1.8, NULL, 'admin_manual', NULL, 1, 'pending', NULL, 1767225600000, 1767225600000);
INSERT OR IGNORE INTO foods (id, barcode, name, brand, category, serving_size_g, serving_label, calories_kcal, protein_g, carbs_g, fat_g, saturated_fat_g, fiber_g, sugar_g, sodium_mg, cholesterol_mg, potassium_mg, calcium_mg, iron_mg, micronutrients_json, source, source_url, is_verified, embedding_status, created_by, created_at, updated_at) VALUES ('0193a000-0001-7000-8000-000000000004', NULL, 'Bún chả', NULL, 'noodle_dish', 100, '1 suất (~450 g)', 132, 8.2, 14.1, 4.7, 1.6, 0.9, 3.4, 480, 24, 168, 26, 1.1, NULL, 'admin_manual', NULL, 1, 'pending', NULL, 1767225600000, 1767225600000);
INSERT OR IGNORE INTO foods (id, barcode, name, brand, category, serving_size_g, serving_label, calories_kcal, protein_g, carbs_g, fat_g, saturated_fat_g, fiber_g, sugar_g, sodium_mg, cholesterol_mg, potassium_mg, calcium_mg, iron_mg, micronutrients_json, source, source_url, is_verified, embedding_status, created_by, created_at, updated_at) VALUES ('0193a000-0001-7000-8000-000000000005', NULL, 'Cơm gà', NULL, 'rice_dish', 100, '1 đĩa (~380 g)', 166, 10.6, 21.3, 4.4, 1.3, 0.6, 0.9, 310, 38, 148, 19, 1, NULL, 'admin_manual', NULL, 1, 'pending', NULL, 1767225600000, 1767225600000);
INSERT OR IGNORE INTO foods (id, barcode, name, brand, category, serving_size_g, serving_label, calories_kcal, protein_g, carbs_g, fat_g, saturated_fat_g, fiber_g, sugar_g, sodium_mg, cholesterol_mg, potassium_mg, calcium_mg, iron_mg, micronutrients_json, source, source_url, is_verified, embedding_status, created_by, created_at, updated_at) VALUES ('0193a000-0001-7000-8000-000000000006', NULL, 'Bún bò Huế', NULL, 'noodle_soup', 100, '1 tô (~550 g)', 86, 5.4, 9.8, 2.7, 1, 0.6, 0.8, 510, 15, 102, 21, 1, NULL, 'admin_manual', NULL, 1, 'pending', NULL, 1767225600000, 1767225600000);
INSERT OR IGNORE INTO foods (id, barcode, name, brand, category, serving_size_g, serving_label, calories_kcal, protein_g, carbs_g, fat_g, saturated_fat_g, fiber_g, sugar_g, sodium_mg, cholesterol_mg, potassium_mg, calcium_mg, iron_mg, micronutrients_json, source, source_url, is_verified, embedding_status, created_by, created_at, updated_at) VALUES ('0193a000-0001-7000-8000-000000000007', NULL, 'Gỏi cuốn tôm thịt', NULL, 'appetizer', 100, '2 cuốn (~120 g)', 108, 7.2, 15.6, 1.8, 0.5, 1.2, 1.6, 290, 32, 120, 28, 0.7, NULL, 'admin_manual', NULL, 1, 'pending', NULL, 1767225600000, 1767225600000);
INSERT OR IGNORE INTO foods (id, barcode, name, brand, category, serving_size_g, serving_label, calories_kcal, protein_g, carbs_g, fat_g, saturated_fat_g, fiber_g, sugar_g, sodium_mg, cholesterol_mg, potassium_mg, calcium_mg, iron_mg, micronutrients_json, source, source_url, is_verified, embedding_status, created_by, created_at, updated_at) VALUES ('0193a000-0001-7000-8000-000000000008', NULL, 'Cơm trắng', NULL, 'rice_dish', 100, '1 chén (~150 g)', 130, 2.7, 28.2, 0.3, 0.1, 0.4, 0.1, 1, 0, 35, 10, 0.2, NULL, 'admin_manual', NULL, 1, 'pending', NULL, 1767225600000, 1767225600000);

-- ============ translations: food names ============
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('foods', '0193a000-0001-7000-8000-000000000001', 'vi', 'name', 'Phở bò');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('foods', '0193a000-0001-7000-8000-000000000001', 'en', 'name', 'Beef pho');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('foods', '0193a000-0001-7000-8000-000000000002', 'vi', 'name', 'Cơm tấm sườn nướng');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('foods', '0193a000-0001-7000-8000-000000000002', 'en', 'name', 'Broken rice with grilled pork');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('foods', '0193a000-0001-7000-8000-000000000003', 'vi', 'name', 'Bánh mì thịt');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('foods', '0193a000-0001-7000-8000-000000000003', 'en', 'name', 'Vietnamese pork banh mi');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('foods', '0193a000-0001-7000-8000-000000000004', 'vi', 'name', 'Bún chả');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('foods', '0193a000-0001-7000-8000-000000000004', 'en', 'name', 'Bun cha (grilled pork with noodles)');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('foods', '0193a000-0001-7000-8000-000000000005', 'vi', 'name', 'Cơm gà');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('foods', '0193a000-0001-7000-8000-000000000005', 'en', 'name', 'Chicken rice');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('foods', '0193a000-0001-7000-8000-000000000006', 'vi', 'name', 'Bún bò Huế');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('foods', '0193a000-0001-7000-8000-000000000006', 'en', 'name', 'Hue-style beef noodle soup');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('foods', '0193a000-0001-7000-8000-000000000007', 'vi', 'name', 'Gỏi cuốn tôm thịt');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('foods', '0193a000-0001-7000-8000-000000000007', 'en', 'name', 'Fresh spring rolls');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('foods', '0193a000-0001-7000-8000-000000000008', 'vi', 'name', 'Cơm trắng');
INSERT OR IGNORE INTO translations (entity_type, entity_id, locale, field, value) VALUES ('foods', '0193a000-0001-7000-8000-000000000008', 'en', 'name', 'Steamed white rice');
